### PR TITLE
Add "gitinfo" view

### PR DESCRIPTION
**Pull request by chigby**
This pull request adds a view to the admin area that, essentially, reads from a file and displays those file contents to the admin. In theory, this file is filled with information about the current git commit/branch that's deployed, something like

```
git log HEAD --oneline --no-walk
```

### CODE REVIEW

**Comment by msheiny** [comment]
@chigby mind if i start slinging commits on-top of this? I think in particular I want to be able to over-ride where the gitinfo file is stored.

**Comment by chigby** [comment]
Go for it.

**Comment by conorsch** [comment]
Will take a look at the WIP presented here, and try to get the tests passing.

**Comment by conorsch** [comment]
Rebased on top of latest master (63b9c0c55f2ab8245f670ff0a5c2d29fcd9e787f). Re-reviewing.

**Pull request merged**
