### PR TITLE
Scans the site immediately on saving

### PR DESCRIPTION
**Pull request by SaptakS**
Scans the site immediately using the scan() function from the management command. Right now, it will scan every time a site is saved (added or edited).

My concern with this implementation is since I scan in the `save()` function, the save action might be slower. Should I instead trigger a command line exec to execute the management command instead? cc @harrislapiroff @chigby 

Refs: #225

### CODE REVIEW

**Comment by chigby** [comment]
To your concern, is it possible to just scan the site when it's being added (rather than edited)? I think that would solve the problem of slow saves when you're just changing, say, the site description or something.

**Comment by maeve-fpf** [comment]
From a deployment perspective, it would be better to not have the scan process happen in the gunicorn container. This is an area where things are a bit different from the traditional droplet deployment. The gunicorn container has its resources limited to only what gunicorn needs (including network access), and can be destroyed and replaced by the cluster at any time, as there are several of them serving requests.

A solution which is actually orthogonal to this (would also have worked before, with the scan started by `/usr/bin/cron` on the same server) is to have the scan job run *much* more often, say hourly, but only check sites that have not been scanned since either (a) a week ago, with some random skew so they don't all happen at once and eventually spread out through the whole week or (b) last edit.

(Actually I guess the schedule is twice a week per site, but, same principle.)

If this came up earlier in development, any reason why we didn't do it? I am assuming the expensive part is the actual scan itself, not setting up a process that will do scans. (Concern about the leaderboard being fair if two sites make the same security improvement on the same day?)

**Comment by SaptakS** [comment]
@maeve-fpf thanks for sharing this. I didn't have much idea about the deployment process.

> A solution which is actually orthogonal to this (would also have worked before, with the scan started by /usr/bin/cron on the same server) is to have the scan job run much more often, say hourly, but only check sites that have not been scanned since either (a) a week ago, with some random skew so they don't all happen at once and eventually spread out through the whole week or (b) last edit.

I feel give the deployment perspective, this sounds like a cleaner solution. We can technically compare the last edited times of Site and Scan data, but we don't store timestamp for the Site model. So maybe the week duration condition sounds more ideal in this case.

> If this came up earlier in development, any reason why we didn't do it? I am assuming the expensive part is the actual scan itself, not setting up a process that will do scans. (Concern about the leaderboard being fair if two sites make the same security improvement on the same day?)

To be fair, this is something @harrislapiroff could probably elaborate on since I wasn't there.

**Comment by harrislapiroff** [comment]
I don't know too much about how we arrived at the frequency of scanning—I think that's @conorsch's arena?—but I do think being able to trigger scans from the admin will be a better UX which in turn will make the site more accurate.

One recent example of an issue caused by asynchronous scanning is we had [some inaccurate entries](https://github.com/freedomofpress/securethenews/issues/263) due to misentered URLs. If the scan ran immediately, an editor could notice an incorrect URL immediately. As it stands now, someone has to remember to check back in after the next scan (which apparently we don't do) and even if we do remember, that means the publishing a page and correcting it could be a several hour process.

Another issue is that we sometimes get erroneous scans (for whatever reason pshtt turns up incorrect results—maybe the news org is testing a new server setup, or the server just hiccups for a second) and in those situations, it's a benefit to be able to run a scan quickly and manually.

Is there any way to address these scenarios while keeping the container setup clean? One thing I can think of is that we have the gunicorn container trigger another container to run the scan, but that seems like it would require quite a bit of extra complexity (and maybe a message queue?) to implement, which may not be worth the effort. Thoughts?

**Comment by eloquence** [comment]
FWIW: It's useful to be able to force a re-scan right after making a fix (e.g. to the site domain, as I did last week for the BBC), which is why the scan-of-save seems desirable even if we change the scan frequency.

**Review by chigby — APPROVED** [review]
I tested this out locally and it worked exactly as expected. Approving this so we can merge and get it into production for the real performance test.

**Pull request merged**
