### PR TITLE
Overhauls development environment

### LINKED ISSUE #83: Replace Vagrant with Docker/Docker Compose
Secure the News currently uses a Vagrant-based development environment. This is less than ideal for a number of reasons:

1. Vagrant continues to be a hassle to set up and use. This is especially true for FPF staff, many of whom use hardened Linux kernels (significant work is required to get grsecurity and any of the virtualized providers to work together) or Qubes (where only the Docker provider works anyway, because you cannot nest Vagrant's virtual machines in a Qubes AppVM).
2. `vagrant destroy -f && vagrant up` (to test configuration changes from scratch) is slow, clocking in at 9m15s on my workstation. A lot of this slow-down is due to re-running slow commands (like `apt-get install`) in the Ansible provisioner. It's my understanding that this kind of repeated task gets optimized in Docker thanks to their layered filesystem approach.

In the long term, FPF is interested in experimenting with moving to container-based infrastructure for several of our current projects, so Secure the News seems like a good testbed for exploring our options and learning the ropes.

### LINKED ISSUE #120: Upgrade to pshtt 0.2.3
We're currently [pinning](https://github.com/freedomofpress/securethenews/blob/e000d74d1303b58a1c75a5365f4e8004c3c8c65c/ansible/roles/securethenews-deploy/tasks/main.yml#L50-L54) our installed version of pshtt to a specific [commit](https://github.com/dhs-ncats/pshtt/commit/7362a8bdabe7190a933e4c5e18561ba9d07dc561), because it contains a fix that we needed to ensure accurate results on Secure the News, and there was a while between when the fix was committed and the pshtt maintainers created a new release.

Now the pshtt maintainers have released [pshtt 0.1.6](https://pypi.python.org/pypi/pshtt/0.1.6), which includes that fix and some others as well.

Notably, pshtt 0.1.6 upgrades the SSLyze dependency to 1.x, so we will have to make sure that transition is smooth.

### LINKED ISSUE #122: Enable Circle CI for automated builds
We're currently using Travis CI only to run the `./manage.py test` suite after installing requirements. That's good, but for other websites we manage, we're also running through a more prod-like CI environment to catch configuration errors prior to deploying.

Let's drop in a `.circle/config.yml` file to start running container-based testing via Molecule (relevant: #83).

### PR DESCRIPTION
**Pull request by conorsch**
## Status

Ready for review.

## Description of Changes

Ditches the Vagrant VM-based development environment, in favor of Docker-via-Molecule. Closes a variety of issues:

* Fixes #120 (upgrade pshtt)
* Fixes #122 (use Circle CI)
* Progress towards #83 (use docker for development) (but does not close)

Changes proposed in this pull request:

* Replaces Vagrant with Molecule
* Updates README for new dev env
* Moves all site code up a level, to `securethenews/`
* Builds pip requirements via pip-compile _inside a container running python3_. (We should be doing the same in other django projects.)

## Testing

1. Make sure all CI passes
  * Travis
  * Circle CI (new)
2. Run `make help` and make sure the commands work for you.

## Deployment

Tons.

### CODE REVIEW

**Comment by conorsch** [comment]
@msheiny Does `molecule test -s ci` pass for you locally? It does for me, yet CI is failing.

**Comment by msheiny** [comment]
Passing for me locally 😕 I can help ya debug when I get more bandwidth on my plate

**Comment by conorsch** [comment]
@msheiny caught an assumption that was resolved in https://github.com/freedomofpress/ansible-role-django/commit/87b7e0da05161f6d24e289b3c4b1e01b62d78726, let's see if CI passes now

**Comment by conorsch** [comment]
@msheiny CI is passing and upstream PR (https://github.com/freedomofpress/ansible-role-django/pull/32) is merged. Ready for re-review!

**Comment by msheiny** [comment]
Re-reviewing now

**Pull request merged**
