### PR TITLE
Sets Harris as codeowner for all changes

### PR DESCRIPTION
**Pull request by conorsch**
Additional reviewers are:

 * @msheiny for tests (with @conorsch as backup)
 * @emkll for further modifications to ownership

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Looks like CI is gonna be unhappy until we update some stuff on this repo :(

**Comment by conorsch** [comment]
Thanks @harrislapiroff , can you open a separate issue to track?

**Comment by harrislapiroff** [comment]
Opened #153

**Comment by msheiny** [comment]
I'm going to force merge this in. It has nothing to do with the failing safety check and is clearly scoped to just affect github metadata.

**Pull request merged**
