### PR TITLE
Update wagtail2.11.5

### LINKED ISSUE #310: Upgrade to latest Wagtail LTS

### PR DESCRIPTION
**Pull request by SaptakS**
Resolves #310 

The only thing I have noticed and I think it's a wagtail autocomplete thing is in the regions autocomplete field when I start typing, the search icon svg stays on top:
image

cc @harrislapiroff

### CODE REVIEW

**Comment by chigby** [comment]
It looks like the problem with the autocomplete icon is that `wagtailautocomplete` is overriding wagtail's built-in CSS, and sometime between 2.7 and 2.11, wagtail changed the specificity with which it styles the `<input>` tags. It used to use the `input` selector, and now it uses `input:not([type="submit"])`. Or at least, this is my guess.

I was able to fix this locally by editing the CSS for the search box from wagtailautocomplete to have higher specificity, i.e. I changed 

```css
.c-wagtailautocomplete__search {
 [...]
}
```

to 

```css
input.c-wagtailautocomplete__search {
  [...]
}
```

But in order to fix this for real, we will want to incorporate something like this into wagtailautocomplete directly and release a new version.

**Comment by SaptakS** [comment]
> I was able to fix this locally by editing the CSS for the search box from wagtailautocomplete to have higher specificity, i.e. I changed

I was curious if we should fix in wagtail-autocomplete or here in repo for the time.

**Comment by harrislapiroff** [comment]
I've released a new version of [wagtail-autocomplete 0.6.1](https://pypi.org/project/wagtail-autocomplete/0.6.1/)

**Comment by SaptakS** [comment]
Should be ready for review again.

**Comment by SaptakS** [comment]
I made a terribly embarassing mistake in wagtail autocomplete PR, which caused some issues. So we will need to wait till https://github.com/wagtail/wagtail-autocomplete/pull/89/files is merged.

**Comment by SaptakS** [comment]
Should be ready for re-reviewing.

**Review by chigby — APPROVED** [review]
The autocomplete panels look good to me now, and along with everything else, I think this is fine to merge.

**Pull request merged**
