### PR TITLE
Updates cryptography, lxml and djangorestframework dependencies

### PR DESCRIPTION
**Pull request by SaptakS**
cryptography is only updated in pipfile.lock. In requirements, cryptography is a dependency of pyopenssl and sslyze. Even though pyopenssl's latest version has a `>=2.8` for cryptography, but the sslyze version that we are using (because pshtt not compatible with more updated versions of sslyze) has a pinned dependency on `==2.5` of cryptography. Not sure there is a good solution for it.

### CODE REVIEW

**Comment by SaptakS** [comment]
Removing cryptography update from Pipfile fixes the CI fails since pipenv is used in CI and cryptography version was mismatching. @harrislapiroff should I add an ignore for now? I feel we will eventually have to address this

**Comment by harrislapiroff** [comment]
Add an ignore for now. Is there an upstream issue in pshtt that we can nag someone about?

**Comment by SaptakS** [comment]
https://github.com/cisagov/pshtt/issues/209 and https://github.com/cisagov/pshtt/pull/211 seems to be addressed towards the incompatibility between the updated version of sslyze and pshtt which caused them to pin the dependency version number

**Review by chigby — APPROVED** [review]
I agree there's not much we can do other than ignore the `cryptography` vulnerability at the moment. The rest of this works just fine.

**Pull request merged**
