### PR TITLE
Add several reputable nonprofit news sources

### PR DESCRIPTION
**Pull request by eloquence**

### CODE REVIEW

**Comment by conorsch** [comment]
Thanks for the recommendations, @eloquence! We've been maintaining the list of sites via the admin GUI interface to the website, so the entries in the CSV are a bit out of date, but we're certainly not tracking the sites you propose. Will leave this open for more feedback from the team, and if we agree these sites should be added, we'll do so manually via the GUI.

**Comment by eloquence** [comment]
Sounds good, thanks! A bit more info about each source:

- Climate Central: combines science + climate journalism; $9.3M revenue; 61K Twitter+120K FB followers. In-depth review: https://lib.reviews/climate-central
- InsideClimate News: climate watchdog journalism; Pulitzer winner; $1.5M revenue; 74K Twitter+69K FB followers. In-depth review: https://lib.reviews/insideclimate-news
- The Trace: journalism about gun violence. No 990 filed yet, spun out of Bloomberg's Everytown NGO. 12K Twitter Followers, 172K FB followers.
- Rewire: journalism about reproductive rights + intersecting issues. $5.95M revenue, 49K Twitter+110K FB followers. In-depth review: https://lib.reviews/rewire
- The Conversation: academic writers, news backgrounders similar to Vox. Australia-based; $2.3M revenue for US entity. 21.K Twitter + 24K FB followers for US edition. In-depth review: https://lib.reviews/the-conversation
- Reveal: run by Center for Investigative Reporting, "West Coast ProPublica". $10M revenue, 20K Twitter followers, 39K FB followers. In-depth review: https://lib.reviews/reveal
- Mother Jones, Democracy Now!: probably no explanation required

**Comment by garrettr** [comment]
This was accidentally added (and then reverted) as part of #109. I can't figure out how to re-open this pull request, but as @conorsch pointed out earlier, `news_sites.csv` is actually _not_ the canonical list of sites being tracked by Secure the News - that list is stored in the production database and maintained through the CMS.

There is a reasonable argument to be made that we should maintain the list of sites being tracked in a text file in the repository, for transparency's sake, but that's not how we're managing it right now.

I'm consulting with the rest of the team right now, but I think it's likely that we'll add all of the sites you suggested to Secure the News because they are all reasonable additions. Cheers!

**Comment by conorsch** [comment]
> I'm consulting with the rest of the team right now, but I think it's likely that we'll add all of the sites you suggested to Secure the News because they are all reasonable additions.

@garrettr @eloquence Confirmed: I'm in favor of adding all the sites in this PR to the site.

> There is a reasonable argument to be made that we should maintain the list of sites being tracked in a text file in the repository, for transparency's sake, but that's not how we're managing it right now.

Let's add them manually for now and consider exporting to CSV periodically. Will open a separate issue for the CSV update tracking.

**Comment by garrettr** [comment]
> Will open a separate issue for the CSV update tracking.

:+1: Alternatively, we could consider adding a management command that would auto-update the set of sites being tracked based on the contents of a CSV file. We already have most of the necessary code to do this in the `loadsites.py` management command, although we should give that a review and add some tests to make sure it handles deletions properly.

**Comment by eloquence** [comment]
That (automatic sync) would be nice. I'd be happy to help maintain the list either way, but I understand if doing this via PR is easier and has fewer security implications than adding users to the web frontend -- and it's generally a more understandable workflow for volunteers, anyway.

I can look into the loadsites.py code later this week if you don't have time to do it.

**Comment by garrettr** [comment]
Totally agree. I don't think there are any security concerns because we maintain control over merging contributions and pushing them into production. Frankly, maintaining the site list via CSV rather than through the Wagtail CMS would probably be a nicer workflow for us too 😁.

Let's wait for @conorsch to file an issue to track this and then we can dig into a bit more.

**Pull request merged**
