### PR TITLE
track adoption of onion services among news organizations via the Onion-Location header

### PR DESCRIPTION
**Pull request by redshiftzero**
Towards #128, please let me know what you think of adding onion service tracking. 

# screenshots

Screen Shot 2020-08-19 at 7 47 59 PM

## per site page

Screen Shot 2020-08-19 at 6 14 01 PM

## leaderboards

Grades are adjusted such that you cannot get an A+ without having an onion service (down to discuss this in more detail)

Screen Shot 2020-08-19 at 7 48 07 PM

## TODO

- [x] edit text (done via wagtail) to broaden the scope of this site to include onion services in addition to HTTPS - will do once on staging
- [x] add some tests (added in 4b4d697)
- [ ] discuss grading. This PR makes it such that if you have all the suggested HSTS options, you can only get an A (so currently A+ will go down to A). To get an A+, you need to have the onion service.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Ready for an initial look over

**Comment by redshiftzero** [comment]
@thisisparker and I were chatting just now and: 
1. the changes in this PR shouldn't interfere with the current STN bot behavior, and
2. once we merge this we'll update the STN twitter bot to tweet out happy messages when news organizations add Onion-Location

**Review by chigby — APPROVED** [review]
Everything in here looks very good to me. I played around with some scans locally and the Onion Location header detection and reporting worked as expected. So on that basis I think this is worth deploying as-is. 

For future enhancements, I do think it would be nice to get some form of verification that the onion location URL is actually up and working. Yet that can come later.

**Comment by maeve-fpf** [comment]
This is very cool! Looks like a rebase will fix the npm_audit check.

**Comment by redshiftzero** [comment]
thanks @chigby and @maeve-fpf - rebased and CI is indeed passing now 😇

**Pull request merged**
