### PR TITLE
Fixes for development environment on macOS

### PR DESCRIPTION
**Pull request by redshiftzero**
Here are the changes to get the development environment working on macOS, take a look.

Note this is a PR into #124

### CODE REVIEW

**Comment by conorsch** [comment]
Thanks for taking the time, @redshiftzero, will review locally and confirm it works on Linux, as well. However, CI is failing. Looks like the age-old problem, where a proposed solution works:

* [ ] on Linux
* [ ] on Mac
* [ ] in CI

**Pick any two.** 😀

**Comment by conorsch** [comment]
@redshiftzero I'm having a heck of a time debugging CI on this branch. The fixes you propose we definitely want, so I'm going to merge the underlying PR (#124), then re-target this branch so I can isolate the CI snags.

**Comment by msheiny** [comment]
CI is getting a lot farther than before with my latest commit 🤞  - looks like the problem was a recent release of a non rc of ansible 2.4 was getting sucked up and causing failures. I filed a ticket against the [django role ](https://github.com/freedomofpress/ansible-role-django/issues/38) and pegged the devops environment to a version under 2.4 using piptools.

**Comment by conorsch** [comment]
Perfect @msheiny, thank you! Merging.

**Pull request merged**
