### PR TITLE
Fixes nightly build of securethenews

### LINKED ISSUE #206: Nightly CI checks for safety are failing
The nightly cron logic in CircleCI for the repo is failing on a missing `safety_check`:

```
Build-agent version 1.0.14060-707644a8 (2019-08-20T18:03:34+0000)
Configuration errors: 1 error occurred:

* Cannot find a job named `safety_check` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```

See https://circleci.com/gh/freedomofpress/securethenews/1041

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #206 

Renamed `safety_check_linters` to `safety_check`

### CODE REVIEW

**Comment by SaptakS** [comment]
@conorsch this is the PR which has one of the CI job in waiting status.

**Comment by conorsch** [comment]
> we'll need @conorsch's override to merge though.

We shouldn't! Taking a look at the stuck CI status now... it's likely a mismatch between the CircleCI YAML settings and the required checks in the branch protection settings.

**Comment by conorsch** [comment]
No more stuck builds! Updated the branch protection settings to match what's presented here. Rebased on top of latest master (f082f2935386831dad6b6a6d3c1c399d0ba9bf25) in order to include #143. As soon as CI passes, should be ready to merge, @harrislapiroff.

**Comment by harrislapiroff** [comment]
Looks good!

**Pull request merged**
