### PR TITLE
Debian base image migration

### PR DESCRIPTION
**Pull request by charles-boyd**
This PR includes changes necessary for the application to build cleanly off the `python3.6:debian-slim` base image.

### CODE REVIEW

**Comment by msheiny** [comment]
Yeah looks like these testinfra tests are failing out. They've never been very good - I'm tempted to rip them out to keep things moving. I would say spend a little bit of time to try and get them working but timebox it and if its too much effort, just pytest `skip` them all and make a ticket to go back and fix them to our queue. I can assist with this next week assuming no :baby: :bird:

**Comment by conorsch** [comment]
> looks like these testinfra tests are failing out.

At a glance, it looks like the container names are wrong—docker-compose will automatically prefix the pardir/project name to the container name. Investigate the test autodiscovery, as we'd want the testinfra tests to be executed by the host, not within the containers via manage.py.

**Comment by conorsch** [comment]
Summarizing synchronous discussion from today, the goal of the pshtt tests to validate that pshtt is executing properly and returning valid JSON results. That's particularly important because pshtt has a complicated dependency graph, that can conceivably conflict with the wagtail python dependencies, causing pshtt not to execute cleanly. 

The pshtt tests need not be invoked by testinfra, though—it may make more sense to port them into the application tests, and invoke `manage.py scan <example site>`, which will call pshtt under the hood. That'd be a fine enough test for our purposes, and may alleviate some of the test autodiscovery issues.

**Comment by msheiny** [comment]
So i missed the conversation yesterday - how do ya'll feel about `XFAIL-ing` the tests and having them fixed in another subsequent PR? I'm concerned about the growing size and scope of this ticket/PR. It's quickly becoming a large feature branch which is going to become more difficult to merge as time goes on.

**Comment by msheiny** [comment]
Out-of-band conversations - @charles-boyd and I decided to move to merge this PR and create a separate ticket to tackle the lingering testinfra tests failures next. I'm going to sprinkle some PRs in here to XFAIL for now to keep things moving.

**Comment by conorsch** [comment]
#198 has been merged, so you're unblocked here for a rebase, @charles-boyd. At your option, either rebase and force-push here, or open a separate, superseding PR.

**Comment by charles-boyd** [comment]
Closing this now that #199 is open.

**Pull request closed without merging**
